# Generated by Django 4.2.6 on 2023-11-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address2',
            new_name='address_2',
        ),
    ]
